# Generated by Django 3.2 on 2021-06-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210619_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalCode',
            new_name='pincode',
        ),
    ]
